# Generated by Django 2.0.7 on 2019-10-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=1000)),
                ('car_model', models.CharField(max_length=1000)),
                ('start_city', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
                ('longitude', models.CharField(max_length=1000)),
                ('currency_code', models.CharField(max_length=1000)),
                ('rate', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
